version: '3.6'

services:
  db:
    image: supabase/postgres:15.1.0.63
    restart: always
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kong:
    image: kong:2.8
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: supabase
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  rest:
    image: postgrest/postgrest:v10.1.1
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:supabase@db:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: super-secret-jwt
    ports:
      - "3500:3000"   # Host port 3500 maps to container port 3000
    depends_on:
      - db

volumes:
  db-data: 