#!/bin/sh
set -e

# Create multiple databases
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE auth;
    CREATE DATABASE "user";
    CREATE DATABASE shipper;
    CREATE DATABASE driver;
    CREATE DATABASE fleet;
    CREATE DATABASE job;
    CREATE DATABASE matching;
    CREATE DATABASE bidding;
    CREATE DATABASE payment;
    CREATE DATABASE rating;
    CREATE DATABASE compliance;

    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE auth TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE "user" TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE shipper TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE driver TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE fleet TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE job TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE matching TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE bidding TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE payment TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE rating TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE compliance TO $POSTGRES_USER;
EOSQL

echo "Multiple databases created successfully!"
